# The following example is minimalist. The security policies
# and resource specifications are not meant to be used in production.
# Please refer to the operator documentation for recommendations on
# production settings.
apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: soohyun
spec:
  images:
    vtctld: vitess/lite:v6.0.20-20200429
    vtgate: vitess/lite:v6.0.20-20200429
    vttablet: vitess/lite:v6.0.20-20200429
    vtbackup: vitess/lite:v6.0.20-20200429
    mysqld:
      mysql56Compatible: vitess/lite:v6.0.20-20200429
    mysqldExporter: prom/mysqld-exporter:v0.11.0
  cells:
  - name: apnortheast2
    gateway:
      authentication:
        static:
          secret:
            name: example-cluster-config
            key: users.json
      replicas: 3
      resources:
        requests:
          cpu: 2
          memory: 4Gi
        limits:
          memory: 8Gi
  vitessDashboard:
    cells:
    - apnortheast2
    extraFlags:
      security_policy: read-only
      proxy_tablets: "true"
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  keyspaces:
  - name: soda
    turndownPolicy: Immediate
    partitionings:
    - equal:
        parts: 1
        shardTemplate:
          databaseInitScriptSecret:
            name: example-cluster-config
            key: init_db.sql
          replication:
            enforceSemiSync: false
            initializeMaster: true
          tabletPools:
          - cell: apnortheast2
            type: externalmaster
            externalDatastore:
              credentialsSecret:
                name: example-cluster-config
                key: aurora.json
              database: soda
              host: test-soohyun-aurora-auroracluster.cluster-clbz1hjlobpr.ap-northeast-2.rds.amazonaws.com
              port: 3306
              user: root
            replicas: 1
            vttablet:
              extraFlags:
                db_charset: utf8mb4
              resources:
                requests:
                  cpu: 2
                  memory: 4Gi
                limits:
                  memory: 8Gi
  - name: messages
    turndownPolicy: Immediate
    partitionings:
    - equal:
        parts: 1
        shardTemplate:
          databaseInitScriptSecret:
            name: example-cluster-config
            key: init_db.sql
          replication:
            enforceSemiSync: false
            initializeMaster: true
          tabletPools:
          - cell: apnortheast2
            type: externalmaster
            externalDatastore:
              credentialsSecret:
                name: example-cluster-config
                key: vt_aurora.json
              database: vt_soda
              host: test-soohyun-vitess-02-cluster.cluster-clbz1hjlobpr.ap-northeast-2.rds.amazonaws.com
              port: 3306
              user: cheiron
            replicas: 1
            vttablet:
              extraFlags:
                db_charset: utf8mb4
              resources:
                requests:
                  cpu: 2
                  memory: 4Gi
                limits:
                  memory: 8Gi
    - equal:
        parts: 2
        shardTemplate:
          databaseInitScriptSecret:
            name: example-cluster-config
            key: init_db.sql
          replication:
            enforceSemiSync: false
            initializeMaster: true
          tabletPools:
          - cell: apnortheast2
            type: externalmaster
            externalDatastore:
              credentialsSecret:
                name: example-cluster-config
                key: vt_aurora.json
              database: vt_soda
              host: test-soohyun-vitess-03-cluster.cluster-clbz1hjlobpr.ap-northeast-2.rds.amazonaws.com
              port: 3306
              user: cheiron
            replicas: 1
            vttablet:
              extraFlags:
                db_charset: utf8mb4
              resources:
                requests:
                  cpu: 2
                  memory: 4Gi
                limits:
                  memory: 8Gi

  updateStrategy:
    type: Immediate
