CREATE TABLE `main_messagingchannellist` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL,
  `count_since_joined` int(11) NOT NULL,
  `unread_message_count` int(11) NOT NULL,
  `last_message_text` longtext COLLATE utf8mb4_bin NOT NULL,
  `last_message_ts` bigint(20) NOT NULL,
  `channel_id` int(11) NOT NULL,
  `ts_message_offset` bigint(20) NOT NULL,
  `is_hidden` tinyint(4) NOT NULL,
  `last_activity_ts` bigint(20) NOT NULL,
  `is_push_on` tinyint(1) NOT NULL,
  `attributes` longtext COLLATE utf8mb4_bin NOT NULL,
  `pending` int(11) NOT NULL,
  `last_message_id` int(11) DEFAULT NULL,
  `read_ts` bigint(20) NOT NULL,
  `invited_ts` bigint(20) NOT NULL,
  `inviter_id` int(11) DEFAULT NULL,
  `count_option` smallint(6) NOT NULL,
  `mention_count` smallint(6) NOT NULL,
  `joined_ts` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `main_messagingchannellist_user_id_5c6f4a35ca660f33_uniq` (`channel_id`,`user_id`),
  KEY `main_messagingchannellist_channel_id_654c75ddc2d63923_idx` (`channel_id`,`count_since_joined`),
  KEY `main_messagingchannellist_last_activity_ts_b7af513235dda71_idx` (`last_activity_ts`),
  KEY `main_messagingchannellist_last_message_ts_3ea83862968350e0_idx` (`last_message_ts`),
  KEY `main_messagingchannellist_user_id_1a122f8b229c48df_idx` (`user_id`,`last_message_ts`,`is_hidden`,`count_since_joined`),
  KEY `main_messagingchannellist_channel_id_2de341162b5346e4_idx` (`channel_id`,`pending`,`user_id`),
  KEY `main_messagingchannellist_inviter_id_5aa16d8fcbc557c8_idx` (`inviter_id`,`pending`,`user_id`,`invited_ts`),
  KEY `main_messagingchannellist_user_id_44927fad2c548742_idx` (`user_id`,`is_hidden`,`count_option`),
  KEY `main_messagingchannellist_channel_id_6a5b36e8a8c0af33_idx` (`channel_id`,`pending`,`count_option`,`unread_message_count`),
  KEY `main_messagingchannellist_user_id_2e5f7ec8c21b869c_idx` (`user_id`,`is_hidden`,`unread_message_count`,`channel_id`),
  KEY `main_messagingchannellist_user_id_3a4741ee1cc4538e_idx` (`user_id`,`last_activity_ts`),
  KEY `main_messagingchannellist_user_id_12f2a4c42c08f4ef_idx` (`user_id`,`channel_id`,`read_ts`),
  KEY `main_messagingchannellist_user_id_2845c308b4ba493f_idx` (`user_id`,`is_hidden`,`pending`,`last_message_ts`),
  KEY `main_messagingchannellist_channel_id_29a172d9a32cd25d_idx` (`channel_id`,`joined_ts`)
) ENGINE=InnoDB AUTO_INCREMENT=112002 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
;